// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton square;
    public JoystickButton x;
    public JoystickButton r2;
    public JoystickButton l2;
    public JoystickButton r1;
    public JoystickButton l1;
    public JoystickButton circle;
    public JoystickButton circle2;
    public JoystickButton triangle;
    public JoystickButton leftStickButton;
    public JoystickButton r22;
    public JoystickButton l22;
    public JoystickButton option2;
    public Joystick ps4_Controller;
    public Joystick ps4_Controller2;
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        ps4_Controller = new Joystick(0);
        ps4_Controller2 = new Joystick(1);
      
        x = new JoystickButton(ps4_Controller, 2);
        square = new JoystickButton(ps4_Controller, 1);
        l2 = new JoystickButton(ps4_Controller, 7);
        r2 = new JoystickButton(ps4_Controller, 8);
        l1 = new JoystickButton(ps4_Controller, 5);
        r1 = new JoystickButton(ps4_Controller, 6); 
        r22 = new JoystickButton(ps4_Controller2, 8);
        l22 = new JoystickButton(ps4_Controller2, 7);
        circle = new JoystickButton(ps4_Controller, 4);
        circle2 = new JoystickButton(ps4_Controller2, 4);
        triangle = new JoystickButton(ps4_Controller, 3);
        leftStickButton = new JoystickButton(ps4_Controller, 11);
        option2 = new JoystickButton(ps4_Controller2, 10);
     
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getps4_Controller() {
        return ps4_Controller;
    }
    
    public double getleftStick(){
    	return ps4_Controller.getRawAxis(1);
    }
    
    public double getRightStick(){
    	return ps4_Controller.getRawAxis(5);
    }
    
    
    public boolean getStickButton(){
    	return ps4_Controller.getRawButton(11);
    }
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}
